# Staging
staging:
  hostname: 46.101.107.178
  user: root
  port: 22
  identityFile: ~/.ssh/id_rsa
  forwardAgent: false
  multiplexing: true
  sshOptions:
    UserKnownHostsFile: ~/.ssh/known_hosts
    StrictHostKeyChecking: no
  identity_file:
    public_key:  ~/.ssh/id_rsa.pub
    private_key: ~/.ssh/id_rsa
    password: ''
  stage: staging
  roles:
    - app
    - db
  deploy_path: /var/www/{{application}}

# Production
production:
  hostname:
  user: root
  port: 22
  identityFile: ~/.ssh/id_rsa
  forwardAgent: false
  multiplexing: true
  sshOptions:
    UserKnownHostsFile: ~/.ssh/known_hosts
    StrictHostKeyChecking: no
  identity_file:
    public_key:  ~/.ssh/id_rsa.pub
    private_key: ~/.ssh/id_rsa
    password: ''
  stage: production
  roles:
    - app
    - db
  deploy_path: /var/www/{{application}}
